name: 宠汪汪

on:
  schedule:
    - cron: '30 * * * * '
  watch:
    types: [started]
  #push:
    #branches: [master]  #项目提交到master分只,自动流程重启流程,所有流程
  #pull_request:
    #branches: [master]  #项目拉取自动更行到master分支   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: 'run 宠汪汪' 
        run: python3 jd_joy.py 
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}

  
     
    
